mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
mongoimport -d booking -c apartment --type csv --file /Users/benjaminmangold/HackReactor/sb-Booking/seed_mongo/sample.csv --headerline
